=== angelhc31/CFGS-Desarrollo-de-Aplicaciones-Web/DAW1/LMSI/Examenes/Examen 3 Evaluación/Ejercicio1/examen3.dtd
<!DOCTYPE Exposiciones[
    <!ELEMENT Exposiciones (expo+)>
        <!ELEMENT expo (Obras, ID_Expo, nombre, lugar, tipo, descripcion, website, fechaInicio, fechaFin, obrasExpuestas)>
            <!ATTLIST expo id NMTOKEN #REQUIRED>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT lugar (#PCDATA)>
            <!ELEMENT tipo (#PCDATA)>
            <!ELEMENT descripcion (#PCDATA)>
            <!ELEMENT website (#PCDATA)>
            <!ELEMENT fechaInicio (#PCDATA)>
            <!ELEMENT fechaFin (#PCDATA)>
            <!ELEMENT obrasExpuestas (#PCDATA)>
        
        <!ELEMENT Obras (obra+)>
            <!ELEMENT obra(Artistas, Estilos, IDObra, titulo, año, estilo, tecnica, IDArtista, IDEstilo)>
                <!ATTLIST obra id NMTOKEN #REQUIRED>
                <!ELEMENT titulo (#PCDATA)>
                <!ELEMENT año (#PCDATA)>
                <!ELEMENT estilo (#PCDATA)>
                <!ELEMENT técnica (#PCDATA)>
        
            <!ELEMENT Artistas (artista+)>
                <!ELEMENT artista (IDArtista, nombre, apellidos, nacionalidad, fechaNacimiento, website)>
                    <!ATTLIST artista id NMTOKEN #REQUIRED>
                    <!ELEMENT nombre (#PCDATA)>
                    <!ELEMENT apellidos (#PCDATA)>
                    <!ELEMENT nacionalidad (#PCDATA)>
                    <!ELEMENT fechaNacimiento (#PCDATA)>
                    <!ELEMENT website (#PCDATA)>

            <!ELEMENT Estilos (estilo?)>
                <!ELEMENT estilo (IDEstilo, nombre, descripcion, tecnica, material)>
                    <!ATTLIST estilo id NMTOKEN #REQUIRED>
                    <!ELEMENT nombre (#PCDATA)>
                    <!ELEMENT descripcion (#PCDATA)>
                    <!ELEMENT tecnica (#PCDATA)>
                    <!ELEMENT material (#PCDATA)>
]>

=== angelhc31/CFGS-Desarrollo-de-Aplicaciones-Web/DAW1/LMSI/Examenes/Examen 3 Evaluación/Ejercicio1/examen3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen3 SYSTEM "examen3.dtd">

<Exposiciones>
    <expo id="1">
        <nombre>El Inutil</nombre>
        <lugar>Benicasim</lugar>
        <tipo>Patetico</tipo>
        <descripcion>Todos los fracasos de este gran artista reunidos<descripcion>
        <website>....</website>
        <fechaInicio>26/5/2021</fechaInicio>
        <fechaFin>27/5/2021</fechaFin>

        <Obras>
            <obra id="1">
                <titulo>Examen de LMSI</titulo>
                <a침o>2021</a침o>
                <estilo>Patetico</estilo>
                <tecnica>Inventada absoulta</tecnica>

                <Artistas>
                    <artista id="1">
                        <nombre>Angel</nombre>
                        <apellidos>Hesse Caracena</apellidos>
                        <nacionalidad>Espa침ol</nacionalidad>
                        <fechaNacimiento>31/12/2002</fechaNacimiento>
                        <website>....</website>
                    </artista>
                </Artistas>

                <Estilos>
                    <estilo id="1">
                        <nombre>Patetico</nombre>
                        <descripcion>Hacerlo todo lo peor que se puede</descripcion>
                        <tecnica>Inventarse todo lo que esta haciendo</tecnica>
                        <material>Imaginaci칩n</material>
                    </estilo>
                </Estilos>
            </obra>
        </Obras>
    </expo>
</Exposiciones>
